import type { Anime } from '@/lib/anime';

const FALLBACK_ANIME: Anime[] = [
  { mal_id: 51009, title: 'Jujutsu Kaisen Season 2', score: 8.8, year: 2023, episodes: 23, synopsis: 'The Shibuya Incident begins as curses attack en masse on Halloween night.', imageUrl: '', genres: ['Action', 'Dark Fantasy'] },
  { mal_id: 52991, title: 'Frieren: Beyond Journey’s End', score: 9.3, year: 2023, episodes: 28, synopsis: 'An elven mage reflects on a decade-long journey after the demon king is defeated.', imageUrl: '', genres: ['Adventure', 'Drama'] }
];

export default function Home() {
  return <main className="shell"><header className="topbar"><div><span className="eyebrow">PRODUCTION FOUNDATION</span><h1>Anime Promo Engine</h1><p>Research, draft, review, and schedule content from one workspace.</p></div><span className="status">● Prototype mode</span></header><section className="notice"><strong>Publishing is not connected.</strong> This foundation creates research results and drafts only. Instagram publishing will be enabled after authentication, storage, approval, and Meta setup.</section><section className="grid"><div className="panel"><span className="eyebrow">STEP 01</span><h2>Research anime</h2><p className="muted">The server-side research endpoint is ready at <code>/api/anime</code>.</p><div className="form-grid"><label>Search<input placeholder="e.g. Frieren" /></label><label>Genre<select defaultValue="action"><option value="action">Action</option><option value="dark">Dark Fantasy</option><option value="comedy">Comedy</option><option value="romance">Romance</option></select></label><label>Minimum score<input type="number" min="0" max="10" step="0.1" defaultValue="7.5" /></label></div><button className="primary" disabled>Research UI coming next</button></div><div className="panel"><span className="eyebrow">CURRENT DRAFT</span><h2>Not selected</h2><p className="muted">Authentication and project storage will be added before any publishing integration.</p></div></section><section className="panel"><div className="panel-head"><div><span className="eyebrow">DISCOVERY PREVIEW</span><h2>Foundation data</h2></div><span className="muted">Offline-safe sample</span></div><div className="cards">{FALLBACK_ANIME.map(anime => <article className="card" key={anime.mal_id}><div className="card-image" /><div className="card-body"><h3>{anime.title}</h3><p>⭐ {anime.score} · {anime.year}</p><small>{anime.synopsis}</small></div></article>)}</div></section><footer>Feature branch · No credentials stored · Demo publishing disabled</footer></main>;
}
